name: Run Auto commit test

on: [workflow_dispatch] # Define when to run the workflow

jobs:
  botcheck-node:
    runs-on: ubuntu-latest # Specify the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Checks-out your repository under $GITHUB_WORKSPACE
      with:
        persist-credentials: true

    - name: Make changes
      run: |
        echo "Adding a new line" >> file.txt  # Example change

    - name: Commit and push if there are changes
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "a.daschevici@gmail.com"
        git config --global user.name "Artur Daschevici"
        git add .
        git commit -m "Automated commit from GitHub Action" || echo "No changes to commit"
        git push
