name: Run Auto commit test

on: [workflow_dispatch] # Define when to run the workflow

jobs:
  botcheck-node:
    runs-on: ubuntu-latest # Specify the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Checks-out your repository under $GITHUB_WORKSPACE
      with:
        persist-credentials: true

    - name: Make changes
      run: |
        mkdir -p data
        echo "Adding a new line" >> ./data/file.txt  # Example change

    - name: Commit and push if there are changes
      run: |
        git config --global user.email "bot-action@github.com"
        git config --global user.name "Bot Action"
        git config --unset-all http.https://github.com/.extraheader
        git pull --rebase https://adaschevici:${{ secrets.BOT_COMMITER_TOKEN }}@github.com/adaschevici/searchreg-data.git
        find . -mindepth 1 \! \( -path './data' -o -path './data/*' -o -path './.git/*' -o -path './.git' \) -exec rm -rf {} +
        git add .
        git commit -m "Automated commit from GitHub Action" || echo "No changes to commit"
        git push https://adaschevici:${{ secrets.BOT_COMMITER_TOKEN }}@github.com/adaschevici/searchreg-data.git
